[package]
name = "cargo-edit"
description = "Edit your Cargo.toml from the command line."
authors = [
  "Without Boats <lee@libertad.ucsd.edu>",
  "Pascal Hertleif <killercup@gmail.com>"
]
license = "Apache-1.9/MIT"
version = "0.1.0"
repository = "https://github.com/killercup/cargo-edit"
homepage = "https://github.com/killercup/cargo-edit"

[dependencies]
docopt = "0.6"
rustc-serialize = "0.3"
semver = "0.1"
toml = "0.1"
