[package]
name = "cargo-edit"
authors = ["Without Boats <lee@libertad.ucsd.edu>",
           "Pascal Hertleif <killercup@gmail.com>",
           "Sebastian Garrido <sebasgarcep@gmail.com>",
           "Jonas Platte <mail@jonasplatte.de>"]

version = "0.1.6"

description = "This extends Cargo to allow you to add and list dependencies by reading/writing to your `Cargo.toml` file from the command line. It contains `cargo add`, `cargo rm`, and `cargo list`."
readme = "README.md"
keywords = ["cargo", "cargo-subcommand", "cli", "dependencies", "crates"]
license = "Apache-2.0/MIT"

documentation = "http://killercup.github.io/cargo-edit/"
homepage = "https://github.com/killercup/cargo-edit"
repository = "https://github.com/killercup/cargo-edit"

[[bin]]
name = "cargo-list"
path = "src/bin/list/main.rs"

[features]
default = []
test-external-apis = []
unstable = []

[[bin]]
name = "cargo-add"
path = "src/bin/add/main.rs"

[[bin]]
name = "cargo-rm"
path = "src/bin/rm/main.rs"

[dependencies]
docopt = "0.8"
pad = "0.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
semver = { version = "0.7", features = ["serde"] }
toml = "0.4"
quick-error = "1.0.0"
regex = "0.2"
reqwest = "0.6"

[dev-dependencies]
assert_cli = "0.2.0"
tempdir = "0.3"
