[package]
authors = ["Without Boats <lee@libertad.ucsd.edu>"]
name = "cargo-add"
version = "0.1.0"
license = "Apache-2.0/MIT"

[dependencies]
docopt = "*"
rustc-serialize = "*"
semver = "*"
toml = "*"
